version: '3.9'

services:
  crawl4ai:
    image: unclecode/crawl4ai:latest

  firecrawl-adapter:
    env_file:
      - api.env
    build: ./api/
    volumes:
      - ./api/main.py:/app/main.py
  search-agent:
    command: mcp_agent_server
    ports:
      - $MCP_PORT:$MCP_PORT
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: agent.dockerfile
    networks:
      - default
      - agent_mcp
      
  tool-server:
    command: mcp_tool_server
    expose:
      - $TOOL_MCP_PORT
    env_file:
      - .env
    build: 
      context: ./
      dockerfile: tools.dockerfile
      
networks: 
  agent_mcp:
    name: agent_mcp
