version: '3.9'

services:
  crawl4ai:
    image: unclecode/crawl4ai:latest

  firecrawl-adapter:
    env_file:
      - api.env
    build: ./api/
    volumes:
      - ./api/main.py:/app/main.py
  search-agent:
    image: nocyphr/mcp_search_agent-agent
    command: mcp_agent_server
    ports:
      - $MCP_PORT:$MCP_PORT
    env_file:
      - .env
    networks:
      - default
      - agent_mcp
      
  tool-server:
    image: nocyphr/mcp_search_agent-tools
    command: mcp_tool_server
    expose:
      - $TOOL_MCP_PORT
    env_file:
      - .env
      
networks: 
  agent_mcp:
    name: agent_mcp
